(defpackage #:3b-bmfont-common
  (:use :cl)
  (:export
   #:glyph
   #:glyph-id
   #:glyph-x
   #:glyph-y
   #:glyph-width
   #:glyph-height
   #:glyph-xoffset
   #:glyph-yoffset
   #:glyph-xadvance
   #:glyph-page
   #:glyph-chnl
   #:glyph-char
   #:glyph-letter
   #:glyph-index
   #:glyph-origin
   #:glyph-origin-y-up
   #:make-glyph
   #:bmfont
   #:info
   #:common
   #:kernings
   #:chars
   #:pages
   #:distance-field
   #:face
   #:size
   #:bold
   #:italic
   #:unicode
   #:charset
   #:stretch-h
   #:smooth
   #:aa
   #:padding
   #:spacing
   #:line-height
   #:base
   #:scale-w
   #:scale-h
   #:packed
   #:alpha-chnl
   #:red-chnl
   #:green-chnl
   #:blue-chnl
   #:kerning-index
   #:kerning-index-characters
   #:%kerning
   #:kerning
   #:remap-char
   #:make-chars-hash
   #:make-kerning-hash
   #:make-keyword
   #:filter-plist
   #:*filters*
   #:char-id
   #:padding-up
   #:padding-right
   #:padding-down
   #:padding-left
   #:v2
   #:update-font-properties))

;; main API package
(defpackage #:3b-bmfont
  (:use :cl #:3b-bmfont-common)
  (:export #:read-bmfont
           #:write-bmfont
           #:glyph
           #:glyph-id
           #:glyph-x
           #:glyph-y
           #:glyph-width
           #:glyph-height
           #:glyph-xoffset
           #:glyph-yoffset
           #:glyph-xadvance
           #:glyph-page
           #:glyph-chnl
           #:glyph-char
           #:glyph-letter
           #:glyph-origin
           #:glyph-origin-y-up
           #:bmfont
           #:info
           #:common
           #:kernings
           #:chars
           #:pages
           #:distance-field
           #:face
           #:size
           #:bold
           #:italic
           #:unicode
           #:charset
           #:stretch-h
           #:smooth
           #:aa
           #:padding
           #:padding-up
           #:padding-right
           #:padding-down
           #:padding-left
           #:spacing
           #:line-height
           #:base
           #:scale-w
           #:scale-h
           #:packed
           #:alpha-chnl
           #:red-chnl
           #:green-chnl
           #:blue-chnl
           #:kerning
           #:kerning-index
           #:map-glyphs
           #:measure-glyphs
           #:space-size
           #:char-data
           #:%kerning
           #:v2))
